apiVersion: v1
kind: Pod
metadata:
  name: secretmount
spec:
  containers:
    - name: secretmount
      image: nginx
      volumeMounts:
        - mountPath: "/etc/foo"
          name: foo
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: thirdsecret