apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
    - name: secret-env
      image: nginx
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: thirdsecret
  restartPolicy: Never